spring:
  profiles:
    active: mysql

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  datasource:
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver  #h2 드라이버 설정
#    url: jdbc:h2:~/test
#
#  h2:
#    console:
#      enabled: true